apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: postgres-backup
  namespace: postgres
  labels:
    app: postgres-backup
    environment: "prod"
spec:
  schedule: "0 */2 * * *"
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          volumes:
          - name: postgres-backup
            persistentVolumeClaim:
              claimName: postgres-backup-claim
          # dnsPolicy: "None"
          # dnsConfig:
          #   nameservers:
          #     - 8.8.8.8
          #     - 8.8.4.4
          restartPolicy: Never
          containers:
          - name:  postgres-backup
            image: 10.0.0.242:5000/postgres-backup:latest
            envFrom:
              - configMapRef:
                  name: postgres-backup
            volumeMounts:
              - name: postgres-backup
                mountPath: /root/pg-backup
