apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-backup-claim
  namespace: postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2G
  storageClassName: nfs-client